### ISSUE TITLE
The translator doesn't work for me and my friend.

### ISSUE THREAD

**Issue by MrRaviol** [BluSpring/UnityTranslate#2]
Hey, so I decided to try this wonderful mod with a friend that doesn't speak my language. However, the mod doesn't translate what we say. It writes what we say perfectly well, but it doesn't translate it. For now it helps with understanding each other, but we still have to speak English.

![Capture d’écran (56)](https://github.com/user-attachments/assets/c482dad8-6845-48f3-91bd-20b4e4c91454)

**Comment by Shisuiicaro** [comment]
This is a forge issue that the dev said it will be fixed, a friend tried the 0.1.7 version and it does work

**Comment by MrRaviol** [comment]
> This is a forge issue that the dev said it will be fixed, a friend tried the 0.1.7 version and it does work

I use Fabric :/
I'll try on the 0.1.7 version then, thanks for the reply

Edit: It does work on the 0.1.7 version, thank you very much!

**Comment by Shisuiicaro** [comment]
Are you playing lan or server?

**Comment by BluSpring** [comment]
This should be fixed in 0.1.9-beta.
