### ISSUE TITLE
Support for PlasmoVoice. SimpleVoiceChat isn't the only VC mod.

### ISSUE THREAD

**Issue by MagmaSlime123** [BluSpring/UnityTranslate#5]

**Comment by BluSpring** [comment]
[Plasmo Voice *is* supported.](https://github.com/BluSpring/UnityTranslate/blob/dev/src/main/kotlin/xyz/bluspring/unitytranslate/compat/voicechat/PlasmoVoiceChatCompat.kt)

**Comment by MagmaSlime123** [comment]
The Modrinth page's description never mentioned it.
